// apps/worker — canonical combined Worker (ingest + API + DO + consumer + cron).
// This router is FINAL and owned by the Phase 0 seed: tasks implement the
// modules it dispatches to, they do not edit this file.
import { startWideEvent, uuidv7 } from "@orange-replay/shared";
import { maintainAnalyticsWarehouse } from "./analytics/maintenance.ts";
import { handleAnalyticsPurgeApi, isAnalyticsPurgeApiPath } from "./analytics/purge-api.ts";
import { handleApi } from "./api/handler.ts";
import { isDashboardAppRoute, serveDashboardAppShell } from "./app-shell.ts";
import { handleFinalizeBatch } from "./consumer/queue.ts";
import { sweepExpiredSessions } from "./consumer/sweeper.ts";
import { isDevTestMode, setWorkerLoggerVersion, type Env, type FinalizeMessage } from "./env.ts";
import { handleIngest, handleRecorderConfig } from "./ingest/handler.ts";
import { RETENTION_SWEEP_SCHEDULE } from "./schedules.ts";
import { handleTestRoutes } from "./test/harness-routes.ts";

export { SessionRecorder } from "./do/session-recorder.ts";
export { PresenceRegistry } from "./do/presence-registry.ts";

const JSON_SECURITY_HEADERS = {
  "x-content-type-options": "nosniff",
  "referrer-policy": "no-referrer",
} as const;

export default {
  async fetch(request, env, ctx): Promise<Response> {
    setWorkerLoggerVersion(env);
    const url = new URL(request.url);
    if (url.pathname === "/v1/ingest") return handleIngest(request, env, ctx);
    if (url.pathname === "/v1/config") return handleRecorderConfig(request, env, ctx);
    if (isAnalyticsPurgeApiPath(url.pathname)) return handleAnalyticsPurgeApi(request, env);
    if (url.pathname.startsWith("/api/")) return handleApi(request, env, ctx);
    if (url.pathname.startsWith("/__test/") && isDevTestMode(env)) {
      return handleTestRoutes(request, env, ctx);
    }
    if (isDashboardAppRoute(url.pathname))
      return serveDashboardAppShell(request, env, url.pathname);
    // Logging contract: every HTTP request emits one wide event — unmatched
    // routes included, so misconfigured SDK endpoints are debuggable.
    const event = startWideEvent("worker", "http.not_found", uuidv7());
    let statusCode = 500;
    let outcome: "client_error" | "server_error" = "server_error";
    try {
      statusCode = 404;
      outcome = "client_error";
      return Response.json(
        { error: "not_found" },
        { status: statusCode, headers: JSON_SECURITY_HEADERS },
      );
    } catch (error) {
      event.fail(error);
      throw error;
    } finally {
      event.set({
        route: safeRoutePath(url.pathname),
        method: request.method,
        status_code: statusCode,
      });
      event.emit(outcome);
    }
  },

  async queue(batch, env, ctx): Promise<void> {
    setWorkerLoggerVersion(env);
    await handleFinalizeBatch(batch, env, ctx);
  },

  async scheduled(controller, env, ctx): Promise<void> {
    setWorkerLoggerVersion(env);
    if (controller.cron === RETENTION_SWEEP_SCHEDULE) {
      ctx.waitUntil(
        (async () => {
          let deletionError: unknown;
          try {
            // Cancel pending exports before this sweep deletes their sidecars.
            await sweepExpiredSessions(env);
          } catch (error) {
            deletionError = error;
          }
          await maintainAnalyticsWarehouse(env);
          if (deletionError !== undefined) throw deletionError;
        })(),
      );
      return;
    }
    ctx.waitUntil(maintainAnalyticsWarehouse(env));
  },
} satisfies ExportedHandler<Env, FinalizeMessage>;

function safeRoutePath(pathname: string): string {
  return pathname.length <= 200 ? pathname : pathname.slice(0, 200);
}
