// apps/worker — canonical combined Worker (ingest + API + DO + consumer + cron).
// This router is FINAL and owned by the Phase 0 seed: tasks implement the
// modules it dispatches to, they do not edit this file.
import { startWideEvent, uuidv7 } from "@orange-replay/shared";
import { handleApi } from "./api/handler.ts";
import { handleFinalizeBatch } from "./consumer/queue.ts";
import { sweepExpiredSessions } from "./consumer/sweeper.ts";
import { isDevTestMode, setWorkerLoggerVersion, type Env, type FinalizeMessage } from "./env.ts";
import { handleIngest } from "./ingest/handler.ts";
import { handleTestRoutes } from "./test/harness-routes.ts";

export { SessionRecorder } from "./do/session-recorder.ts";
export { PresenceRegistry } from "./do/presence-registry.ts";

const JSON_SECURITY_HEADERS = {
  "x-content-type-options": "nosniff",
  "referrer-policy": "no-referrer",
} as const;

export default {
  async fetch(request, env, ctx): Promise<Response> {
    setWorkerLoggerVersion(env);
    const url = new URL(request.url);
    if (url.pathname === "/v1/ingest") return handleIngest(request, env, ctx);
    if (url.pathname.startsWith("/api/")) return handleApi(request, env, ctx);
    if (url.pathname.startsWith("/__test/") && isDevTestMode(env)) {
      return handleTestRoutes(request, env, ctx);
    }
    // Logging contract: every HTTP request emits one wide event — unmatched
    // routes included, so misconfigured SDK endpoints are debuggable.
    const event = startWideEvent("worker", "http.not_found", uuidv7());
    let statusCode = 500;
    let outcome: "client_error" | "server_error" = "server_error";
    try {
      statusCode = 404;
      outcome = "client_error";
      return Response.json(
        { error: "not_found" },
        { status: statusCode, headers: JSON_SECURITY_HEADERS },
      );
    } catch (error) {
      event.fail(error);
      throw error;
    } finally {
      event.set({
        route: safeRoutePath(url.pathname),
        method: request.method,
        status_code: statusCode,
      });
      event.emit(outcome);
    }
  },

  async queue(batch, env, ctx): Promise<void> {
    setWorkerLoggerVersion(env);
    await handleFinalizeBatch(batch, env, ctx);
  },

  async scheduled(_controller, env, ctx): Promise<void> {
    setWorkerLoggerVersion(env);
    ctx.waitUntil(sweepExpiredSessions(env));
  },
} satisfies ExportedHandler<Env, FinalizeMessage>;

function safeRoutePath(pathname: string): string {
  return pathname.length <= 200 ? pathname : pathname.slice(0, 200);
}
