// apps/worker — canonical combined Worker (ingest + API + DO + consumer + cron).
// This router is FINAL and owned by the Phase 0 seed: tasks implement the
// modules it dispatches to, they do not edit this file.
import { handleApi } from "./api/handler.ts";
import { handleFinalizeBatch } from "./consumer/queue.ts";
import { sweepExpiredSessions } from "./consumer/sweeper.ts";
import type { Env, FinalizeMessage } from "./env.ts";
import { handleIngest } from "./ingest/handler.ts";
import { handleTestRoutes } from "./test/harness-routes.ts";

export { SessionRecorder } from "./do/session-recorder.ts";

export default {
  async fetch(request, env, ctx): Promise<Response> {
    const url = new URL(request.url);
    if (url.pathname === "/v1/ingest") return handleIngest(request, env, ctx);
    if (url.pathname.startsWith("/api/")) return handleApi(request, env, ctx);
    if (url.pathname.startsWith("/__test/") && env.DEV_TEST_ROUTES === "1") {
      return handleTestRoutes(request, env, ctx);
    }
    if (url.pathname === "/") {
      return Response.json({ service: "orange-replay", ok: true });
    }
    return Response.json({ error: "not_found" }, { status: 404 });
  },

  async queue(batch, env, ctx): Promise<void> {
    await handleFinalizeBatch(batch, env, ctx);
  },

  async scheduled(_controller, env, ctx): Promise<void> {
    ctx.waitUntil(sweepExpiredSessions(env));
  },
} satisfies ExportedHandler<Env, FinalizeMessage>;
