const TEST_DATABASE_SCHEMA = [
  "CREATE TABLE IF NOT EXISTS orgs (id TEXT PRIMARY KEY NOT NULL, name TEXT NOT NULL, slug TEXT NOT NULL DEFAULT ('legacy-' || lower(hex(randomblob(16)))), logo TEXT, metadata TEXT, shard INTEGER NOT NULL DEFAULT 0, created_at INTEGER NOT NULL)",
  "CREATE UNIQUE INDEX IF NOT EXISTS idx_orgs_slug ON orgs(slug)",
  'CREATE TABLE IF NOT EXISTS projects (id TEXT PRIMARY KEY, org_id TEXT NOT NULL, name TEXT NOT NULL, jurisdiction TEXT, retention_days INTEGER NOT NULL DEFAULT 30, sample_rate REAL NOT NULL DEFAULT 1.0, allowed_origins TEXT NOT NULL, mask_policy_version INTEGER NOT NULL DEFAULT 1, mask_rules TEXT NOT NULL DEFAULT \'[]\', capture_toggles TEXT NOT NULL DEFAULT \'{"heatmaps":false,"console":false,"network":false,"canvas":false}\', quota_state TEXT NOT NULL DEFAULT \'ok\', config_version INTEGER NOT NULL DEFAULT 1, created_at INTEGER NOT NULL)',
  "CREATE INDEX IF NOT EXISTS idx_projects_org_id ON projects(org_id)",
  "CREATE TABLE IF NOT EXISTS keys (key_hash TEXT PRIMARY KEY NOT NULL, id TEXT NOT NULL DEFAULT ('key_legacy_' || lower(hex(randomblob(16)))), project_id TEXT NOT NULL, name TEXT NOT NULL DEFAULT 'Legacy key', active INTEGER NOT NULL DEFAULT 1, created_by TEXT, created_at INTEGER NOT NULL, revoked_at INTEGER, revoked_by TEXT, cache_synced INTEGER NOT NULL DEFAULT 1, cache_final_check_at INTEGER)",
  "CREATE UNIQUE INDEX IF NOT EXISTS idx_keys_id ON keys(id)",
  "CREATE INDEX IF NOT EXISTS idx_keys_project_active ON keys(project_id, active)",
  "CREATE INDEX IF NOT EXISTS idx_keys_cache_sync ON keys(active, cache_synced, revoked_at)",
  "CREATE INDEX IF NOT EXISTS idx_keys_cache_final_check ON keys(active, cache_final_check_at)",
  "CREATE TABLE IF NOT EXISTS key_cache_writes (id TEXT PRIMARY KEY NOT NULL, key_hash TEXT NOT NULL REFERENCES keys(key_hash) ON DELETE CASCADE, started_at INTEGER NOT NULL)",
  "CREATE INDEX IF NOT EXISTS idx_key_cache_writes_hash ON key_cache_writes(key_hash)",
  "CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY NOT NULL, name TEXT NOT NULL, email TEXT NOT NULL, email_verified INTEGER NOT NULL DEFAULT 0, image TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, role TEXT, banned INTEGER NOT NULL DEFAULT 0, ban_reason TEXT, ban_expires INTEGER)",
  "CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON users(email)",
  "CREATE INDEX IF NOT EXISTS idx_users_created_at ON users(created_at)",
  "CREATE TABLE IF NOT EXISTS auth_sessions (id TEXT PRIMARY KEY NOT NULL, expires_at INTEGER NOT NULL, token TEXT NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL, ip_address TEXT, user_agent TEXT, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, active_org_id TEXT, impersonated_by TEXT)",
  "CREATE UNIQUE INDEX IF NOT EXISTS idx_auth_sessions_token ON auth_sessions(token)",
  "CREATE INDEX IF NOT EXISTS idx_auth_sessions_user_id ON auth_sessions(user_id)",
  "CREATE INDEX IF NOT EXISTS idx_auth_sessions_expires_at ON auth_sessions(expires_at)",
  "CREATE TABLE IF NOT EXISTS auth_accounts (id TEXT PRIMARY KEY NOT NULL, account_id TEXT NOT NULL, provider_id TEXT NOT NULL, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, access_token TEXT, refresh_token TEXT, id_token TEXT, access_token_expires_at INTEGER, refresh_token_expires_at INTEGER, scope TEXT, password TEXT, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)",
  "CREATE UNIQUE INDEX IF NOT EXISTS idx_auth_accounts_provider_account ON auth_accounts(provider_id, account_id)",
  "CREATE INDEX IF NOT EXISTS idx_auth_accounts_user_id ON auth_accounts(user_id)",
  "CREATE TABLE IF NOT EXISTS auth_verifications (id TEXT PRIMARY KEY NOT NULL, identifier TEXT NOT NULL, value TEXT NOT NULL, expires_at INTEGER NOT NULL, created_at INTEGER NOT NULL, updated_at INTEGER NOT NULL)",
  "CREATE INDEX IF NOT EXISTS idx_auth_verifications_identifier ON auth_verifications(identifier)",
  "CREATE TABLE IF NOT EXISTS auth_rate_limits (id TEXT PRIMARY KEY NOT NULL, key TEXT NOT NULL, count INTEGER NOT NULL, last_request INTEGER NOT NULL)",
  "CREATE UNIQUE INDEX IF NOT EXISTS idx_auth_rate_limits_key ON auth_rate_limits(key)",
  "CREATE TABLE IF NOT EXISTS members (id TEXT PRIMARY KEY NOT NULL, org_id TEXT NOT NULL REFERENCES orgs(id) ON DELETE CASCADE, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, role TEXT NOT NULL DEFAULT 'member', created_at INTEGER NOT NULL)",
  "CREATE UNIQUE INDEX IF NOT EXISTS idx_members_org_user ON members(org_id, user_id)",
  "CREATE INDEX IF NOT EXISTS idx_members_user_id ON members(user_id)",
  "CREATE INDEX IF NOT EXISTS idx_members_org_id ON members(org_id)",
  "CREATE TABLE IF NOT EXISTS invitations (id TEXT PRIMARY KEY NOT NULL, org_id TEXT NOT NULL REFERENCES orgs(id) ON DELETE CASCADE, email TEXT NOT NULL, role TEXT, status TEXT NOT NULL DEFAULT 'pending', expires_at INTEGER NOT NULL, created_at INTEGER NOT NULL, inviter_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE)",
  "CREATE INDEX IF NOT EXISTS idx_invitations_org_id ON invitations(org_id)",
  "CREATE INDEX IF NOT EXISTS idx_invitations_email ON invitations(email)",
  "CREATE TABLE IF NOT EXISTS sessions (session_id TEXT NOT NULL, project_id TEXT NOT NULL, org_id TEXT NOT NULL, started_at INTEGER NOT NULL, ended_at INTEGER NOT NULL, duration_ms INTEGER NOT NULL, country TEXT, region TEXT, city TEXT, device TEXT, browser TEXT, os TEXT, entry_url TEXT, url_count INTEGER NOT NULL DEFAULT 0, page_count INTEGER, analytics_version INTEGER NOT NULL DEFAULT 0, max_scroll_depth INTEGER, quick_backs INTEGER, interaction_time_ms INTEGER, activity_hist TEXT, clicks INTEGER NOT NULL DEFAULT 0, errors INTEGER NOT NULL DEFAULT 0, rages INTEGER NOT NULL DEFAULT 0, navs INTEGER NOT NULL DEFAULT 0, bytes INTEGER NOT NULL DEFAULT 0, segment_count INTEGER NOT NULL DEFAULT 0, flags INTEGER NOT NULL DEFAULT 0, manifest_key TEXT NOT NULL, expires_at INTEGER NOT NULL, indexed_at INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (project_id, session_id))",
  "CREATE INDEX IF NOT EXISTS idx_sessions_project_time ON sessions(project_id, started_at DESC, session_id DESC)",
  "CREATE INDEX IF NOT EXISTS idx_sessions_project_indexed_at ON sessions(project_id, indexed_at DESC, session_id DESC)",
  "CREATE INDEX IF NOT EXISTS idx_sessions_project_country_time ON sessions(project_id, country, started_at DESC, session_id DESC)",
  "CREATE INDEX IF NOT EXISTS idx_sessions_project_region_time ON sessions(project_id, region, started_at DESC, session_id DESC)",
  "CREATE INDEX IF NOT EXISTS idx_sessions_project_device_time ON sessions(project_id, device, started_at DESC, session_id DESC)",
  "CREATE INDEX IF NOT EXISTS idx_sessions_project_browser_time ON sessions(project_id, browser, started_at DESC, session_id DESC)",
  "CREATE INDEX IF NOT EXISTS idx_sessions_project_os_time ON sessions(project_id, os, started_at DESC, session_id DESC)",
  "CREATE INDEX IF NOT EXISTS idx_sessions_project_entry_url_time ON sessions(project_id, entry_url, started_at DESC, session_id DESC)",
  "CREATE INDEX IF NOT EXISTS idx_sessions_project_errors_time ON sessions(project_id, errors, started_at DESC, session_id DESC)",
  "CREATE INDEX IF NOT EXISTS idx_sessions_project_duration_time ON sessions(project_id, duration_ms, started_at DESC, session_id DESC)",
  "CREATE INDEX IF NOT EXISTS idx_sessions_project_rages_time ON sessions(project_id, rages, started_at DESC, session_id DESC)",
  "CREATE INDEX IF NOT EXISTS idx_sessions_project_quick_backs_time ON sessions(project_id, quick_backs, started_at DESC, session_id DESC)",
  "CREATE INDEX IF NOT EXISTS idx_sessions_project_analytics_version_time ON sessions(project_id, analytics_version, started_at DESC, session_id DESC)",
  "CREATE INDEX IF NOT EXISTS idx_sessions_expiry ON sessions(expires_at)",
  "CREATE TABLE IF NOT EXISTS project_public_pages (project_id TEXT PRIMARY KEY NOT NULL REFERENCES projects(id) ON DELETE CASCADE, public_id TEXT NOT NULL, is_enabled INTEGER NOT NULL DEFAULT 0 CHECK (is_enabled IN (0, 1)), revision INTEGER NOT NULL DEFAULT 1 CHECK (revision > 0), published_at INTEGER, updated_at INTEGER NOT NULL)",
  "CREATE UNIQUE INDEX IF NOT EXISTS idx_project_public_pages_public_id ON project_public_pages(public_id)",
  "CREATE INDEX IF NOT EXISTS idx_project_public_pages_enabled ON project_public_pages(is_enabled, public_id)",
  "CREATE TABLE IF NOT EXISTS public_page_sessions (project_id TEXT NOT NULL REFERENCES project_public_pages(project_id) ON DELETE CASCADE, session_id TEXT NOT NULL, public_replay_id TEXT NOT NULL, position INTEGER NOT NULL CHECK (position BETWEEN 0 AND 9), added_at INTEGER NOT NULL, PRIMARY KEY (project_id, session_id), FOREIGN KEY (project_id, session_id) REFERENCES sessions(project_id, session_id) ON DELETE CASCADE)",
  "CREATE UNIQUE INDEX IF NOT EXISTS idx_public_page_sessions_replay_id ON public_page_sessions(public_replay_id)",
  "CREATE UNIQUE INDEX IF NOT EXISTS idx_public_page_sessions_position ON public_page_sessions(project_id, position)",
  "CREATE TABLE IF NOT EXISTS session_events (project_id TEXT NOT NULL, session_id TEXT NOT NULL, t INTEGER NOT NULL, kind TEXT NOT NULL, detail TEXT, PRIMARY KEY (project_id, session_id, t, kind))",
  "CREATE TABLE IF NOT EXISTS session_deletions (project_id TEXT NOT NULL, session_id TEXT NOT NULL, requested_at INTEGER NOT NULL, attempts INTEGER NOT NULL DEFAULT 0, last_error TEXT, PRIMARY KEY (project_id, session_id))",
  "CREATE TABLE IF NOT EXISTS usage_monthly (org_id TEXT NOT NULL, month TEXT NOT NULL, sessions INTEGER NOT NULL DEFAULT 0, bytes INTEGER NOT NULL DEFAULT 0, PRIMARY KEY (org_id, month))",
  "CREATE TABLE IF NOT EXISTS analytics_export_outbox (export_sequence INTEGER PRIMARY KEY AUTOINCREMENT, export_id TEXT NOT NULL UNIQUE, project_id TEXT NOT NULL, session_id TEXT NOT NULL, record_kind TEXT NOT NULL CHECK (record_kind IN ('session', 'event', 'deletion')), payload_json TEXT NOT NULL CHECK (json_valid(payload_json) AND length(CAST(payload_json AS BLOB)) <= 32768), created_at INTEGER NOT NULL, sent_at INTEGER, attempt_count INTEGER NOT NULL DEFAULT 0, last_error TEXT, quarantined_at INTEGER, quarantine_reason TEXT, sidecar_event_offset INTEGER NOT NULL DEFAULT 0 CHECK (sidecar_event_offset >= 0))",
  "CREATE INDEX IF NOT EXISTS idx_analytics_export_outbox_pending ON analytics_export_outbox(export_sequence) WHERE sent_at IS NULL AND quarantined_at IS NULL",
  "CREATE INDEX IF NOT EXISTS idx_analytics_export_outbox_project_sequence ON analytics_export_outbox(project_id, export_sequence)",
  "CREATE INDEX IF NOT EXISTS idx_analytics_export_outbox_project_kind_sequence ON analytics_export_outbox(project_id, record_kind, export_sequence DESC)",
  "CREATE INDEX IF NOT EXISTS idx_analytics_export_outbox_session_sequence ON analytics_export_outbox(project_id, session_id, record_kind, export_sequence)",
  "CREATE TABLE IF NOT EXISTS analytics_export_ledger (export_id TEXT PRIMARY KEY, export_sequence INTEGER NOT NULL UNIQUE CHECK (export_sequence > 0), project_id TEXT NOT NULL, session_id TEXT NOT NULL, record_kind TEXT NOT NULL CHECK (record_kind IN ('session', 'event', 'deletion')), sent_at INTEGER NOT NULL, first_seen_verified_at INTEGER NOT NULL)",
  "CREATE INDEX IF NOT EXISTS idx_analytics_export_ledger_session_sequence ON analytics_export_ledger(project_id, session_id, record_kind, export_sequence)",
  "CREATE INDEX IF NOT EXISTS idx_analytics_export_ledger_project_kind_sequence ON analytics_export_ledger(project_id, record_kind, export_sequence DESC)",
  "CREATE TABLE IF NOT EXISTS analytics_warehouse_state (project_id TEXT PRIMARY KEY, verified_sequence INTEGER NOT NULL DEFAULT 0, verified_at INTEGER, last_attempt_at INTEGER, last_error TEXT)",
  "CREATE TABLE IF NOT EXISTS analytics_export_lease (shard INTEGER PRIMARY KEY CHECK (shard = 0), owner_id TEXT NOT NULL CHECK (length(owner_id) BETWEEN 1 AND 200), acquired_at INTEGER NOT NULL CHECK (acquired_at > 0), expires_at INTEGER NOT NULL CHECK (expires_at > acquired_at), send_available_at INTEGER NOT NULL DEFAULT 0 CHECK (send_available_at >= 0))",
  "CREATE TABLE IF NOT EXISTS analytics_deletion_jobs (project_id TEXT NOT NULL, session_id TEXT NOT NULL, requested_at INTEGER NOT NULL CHECK (requested_at > 0), delete_reason TEXT NOT NULL CHECK (length(delete_reason) BETWEEN 1 AND 200), requires_warehouse_tombstone INTEGER NOT NULL DEFAULT 1 CHECK (requires_warehouse_tombstone IN (0, 1)), deletion_export_sequence INTEGER CHECK (deletion_export_sequence > 0), purge_attempts INTEGER NOT NULL DEFAULT 0 CHECK (purge_attempts >= 0), purge_last_attempt_at INTEGER, purge_last_error TEXT, first_zero_at INTEGER, completed_at INTEGER, lease_owner TEXT, lease_expires_at INTEGER, alerted_at INTEGER, PRIMARY KEY (project_id, session_id))",
  "CREATE INDEX IF NOT EXISTS idx_analytics_deletion_jobs_pending ON analytics_deletion_jobs(requested_at, project_id, session_id) WHERE completed_at IS NULL",
  "CREATE TABLE IF NOT EXISTS analytics_backfill_completions (project_id TEXT PRIMARY KEY, source_session_count INTEGER NOT NULL CHECK (source_session_count >= 0), source_cutoff_ms INTEGER NOT NULL CHECK (source_cutoff_ms > 0), required_sequence INTEGER NOT NULL CHECK (required_sequence >= 0), report_id TEXT NOT NULL CHECK (length(report_id) BETWEEN 1 AND 200), completed_at INTEGER NOT NULL CHECK (completed_at > 0))",
] as const;

export async function createTestDatabaseSchema(db: D1Database): Promise<void> {
  for (const statement of TEST_DATABASE_SCHEMA) {
    await db.prepare(statement).run();
  }
}
