ALTER TABLE sessions ADD COLUMN page_count INTEGER;
ALTER TABLE sessions ADD COLUMN analytics_version INTEGER NOT NULL DEFAULT 0;
CREATE INDEX IF NOT EXISTS idx_sessions_project_country_time ON sessions(project_id, country, started_at DESC, session_id DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_project_region_time ON sessions(project_id, region, started_at DESC, session_id DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_project_device_time ON sessions(project_id, device, started_at DESC, session_id DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_project_browser_time ON sessions(project_id, browser, started_at DESC, session_id DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_project_os_time ON sessions(project_id, os, started_at DESC, session_id DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_project_entry_url_time ON sessions(project_id, entry_url, started_at DESC, session_id DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_project_errors_time ON sessions(project_id, errors, started_at DESC, session_id DESC);
CREATE INDEX IF NOT EXISTS idx_sessions_project_duration_time ON sessions(project_id, duration_ms, started_at DESC, session_id DESC);
