export const DEFAULT_RECORDING_RETENTION_DAYS = 90;
export const ANALYTICS_RETENTION_DAYS = 730;

export const RETENTION_DAY_MS = 24 * 60 * 60 * 1_000;
export const ANALYTICS_RETENTION_MS = ANALYTICS_RETENTION_DAYS * RETENTION_DAY_MS;
