/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: bc54e1b8d8ddd6bcd4d33c5766ba6e06)
interface __BaseEnv_Env {
  CF_VERSION_METADATA: WorkerVersionMetadata;
  ORANGE_REPLAY_PURGE_API_URL: string;
  ANALYTICS_PURGE_RUNNER_TOKEN: string;
  R2_CATALOG_URI: string;
  R2_SQL_WAREHOUSE: string;
  ORANGE_REPLAY_CATALOG_TOKEN: string;
  ANALYTICS_PURGE_CONTAINER: DurableObjectNamespace<import("./src/index").AnalyticsPurgeContainer>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "AnalyticsPurgeContainer";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<
      Cloudflare.Env,
      | "ORANGE_REPLAY_PURGE_API_URL"
      | "ANALYTICS_PURGE_RUNNER_TOKEN"
      | "R2_CATALOG_URI"
      | "R2_SQL_WAREHOUSE"
      | "ORANGE_REPLAY_CATALOG_TOKEN"
    >
  > {}
}
